// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline_msg.proto

package pipeline_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtobufPipelineMessage_Vertical int32

const (
	ProtobufPipelineMessage_is24 ProtobufPipelineMessage_Vertical = 0
	ProtobufPipelineMessage_as24 ProtobufPipelineMessage_Vertical = 1
	ProtobufPipelineMessage_s24  ProtobufPipelineMessage_Vertical = 2
)

var ProtobufPipelineMessage_Vertical_name = map[int32]string{
	0: "is24",
	1: "as24",
	2: "s24",
}

var ProtobufPipelineMessage_Vertical_value = map[string]int32{
	"is24": 0,
	"as24": 1,
	"s24":  2,
}

func (x ProtobufPipelineMessage_Vertical) String() string {
	return proto.EnumName(ProtobufPipelineMessage_Vertical_name, int32(x))
}

func (ProtobufPipelineMessage_Vertical) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0, 0}
}

type ProtobufPipelineMessage_LogLevel int32

const (
	ProtobufPipelineMessage_TRACE ProtobufPipelineMessage_LogLevel = 0
	ProtobufPipelineMessage_DEBUG ProtobufPipelineMessage_LogLevel = 1
	ProtobufPipelineMessage_INFO  ProtobufPipelineMessage_LogLevel = 2
	ProtobufPipelineMessage_WARN  ProtobufPipelineMessage_LogLevel = 3
	ProtobufPipelineMessage_ERROR ProtobufPipelineMessage_LogLevel = 4
	ProtobufPipelineMessage_FATAL ProtobufPipelineMessage_LogLevel = 5
)

var ProtobufPipelineMessage_LogLevel_name = map[int32]string{
	0: "TRACE",
	1: "DEBUG",
	2: "INFO",
	3: "WARN",
	4: "ERROR",
	5: "FATAL",
}

var ProtobufPipelineMessage_LogLevel_value = map[string]int32{
	"TRACE": 0,
	"DEBUG": 1,
	"INFO":  2,
	"WARN":  3,
	"ERROR": 4,
	"FATAL": 5,
}

func (x ProtobufPipelineMessage_LogLevel) String() string {
	return proto.EnumName(ProtobufPipelineMessage_LogLevel_name, int32(x))
}

func (ProtobufPipelineMessage_LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0, 1}
}

type ProtobufPipelineMessage_MetricType int32

const (
	ProtobufPipelineMessage_COUNTER ProtobufPipelineMessage_MetricType = 0
	ProtobufPipelineMessage_GAUGE   ProtobufPipelineMessage_MetricType = 1
)

var ProtobufPipelineMessage_MetricType_name = map[int32]string{
	0: "COUNTER",
	1: "GAUGE",
}

var ProtobufPipelineMessage_MetricType_value = map[string]int32{
	"COUNTER": 0,
	"GAUGE":   1,
}

func (x ProtobufPipelineMessage_MetricType) String() string {
	return proto.EnumName(ProtobufPipelineMessage_MetricType_name, int32(x))
}

func (ProtobufPipelineMessage_MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0, 2}
}

type ProtobufPipelineMessage struct {
	Version              int32                             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProducerId           string                            `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Timestamp            *timestamp.Timestamp              `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Product              string                            `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	Team                 string                            `protobuf:"bytes,5,opt,name=team,proto3" json:"team,omitempty"`
	Service              string                            `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Vertical             ProtobufPipelineMessage_Vertical  `protobuf:"varint,7,opt,name=vertical,proto3,enum=pipeline_msg.ProtobufPipelineMessage_Vertical" json:"vertical,omitempty"`
	LogLevel             ProtobufPipelineMessage_LogLevel  `protobuf:"varint,8,opt,name=log_level,json=logLevel,proto3,enum=pipeline_msg.ProtobufPipelineMessage_LogLevel" json:"log_level,omitempty"`
	LogMsg               string                            `protobuf:"bytes,9,opt,name=log_msg,json=logMsg,proto3" json:"log_msg,omitempty"`
	Fields               []*ProtobufPipelineMessage_Field  `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty"`
	Metrics              []*ProtobufPipelineMessage_Metric `protobuf:"bytes,11,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ProtobufPipelineMessage) Reset()         { *m = ProtobufPipelineMessage{} }
func (m *ProtobufPipelineMessage) String() string { return proto.CompactTextString(m) }
func (*ProtobufPipelineMessage) ProtoMessage()    {}
func (*ProtobufPipelineMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0}
}

func (m *ProtobufPipelineMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtobufPipelineMessage.Unmarshal(m, b)
}
func (m *ProtobufPipelineMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtobufPipelineMessage.Marshal(b, m, deterministic)
}
func (m *ProtobufPipelineMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtobufPipelineMessage.Merge(m, src)
}
func (m *ProtobufPipelineMessage) XXX_Size() int {
	return xxx_messageInfo_ProtobufPipelineMessage.Size(m)
}
func (m *ProtobufPipelineMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtobufPipelineMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtobufPipelineMessage proto.InternalMessageInfo

func (m *ProtobufPipelineMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ProtobufPipelineMessage) GetProducerId() string {
	if m != nil {
		return m.ProducerId
	}
	return ""
}

func (m *ProtobufPipelineMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ProtobufPipelineMessage) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ProtobufPipelineMessage) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *ProtobufPipelineMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ProtobufPipelineMessage) GetVertical() ProtobufPipelineMessage_Vertical {
	if m != nil {
		return m.Vertical
	}
	return ProtobufPipelineMessage_is24
}

func (m *ProtobufPipelineMessage) GetLogLevel() ProtobufPipelineMessage_LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return ProtobufPipelineMessage_TRACE
}

func (m *ProtobufPipelineMessage) GetLogMsg() string {
	if m != nil {
		return m.LogMsg
	}
	return ""
}

func (m *ProtobufPipelineMessage) GetFields() []*ProtobufPipelineMessage_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ProtobufPipelineMessage) GetMetrics() []*ProtobufPipelineMessage_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ProtobufPipelineMessage_Field struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtobufPipelineMessage_Field) Reset()         { *m = ProtobufPipelineMessage_Field{} }
func (m *ProtobufPipelineMessage_Field) String() string { return proto.CompactTextString(m) }
func (*ProtobufPipelineMessage_Field) ProtoMessage()    {}
func (*ProtobufPipelineMessage_Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0, 0}
}

func (m *ProtobufPipelineMessage_Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtobufPipelineMessage_Field.Unmarshal(m, b)
}
func (m *ProtobufPipelineMessage_Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtobufPipelineMessage_Field.Marshal(b, m, deterministic)
}
func (m *ProtobufPipelineMessage_Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtobufPipelineMessage_Field.Merge(m, src)
}
func (m *ProtobufPipelineMessage_Field) XXX_Size() int {
	return xxx_messageInfo_ProtobufPipelineMessage_Field.Size(m)
}
func (m *ProtobufPipelineMessage_Field) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtobufPipelineMessage_Field.DiscardUnknown(m)
}

var xxx_messageInfo_ProtobufPipelineMessage_Field proto.InternalMessageInfo

func (m *ProtobufPipelineMessage_Field) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProtobufPipelineMessage_Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ProtobufPipelineMessage_Metric struct {
	Key                  string                             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                float64                            `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 ProtobufPipelineMessage_MetricType `protobuf:"varint,3,opt,name=type,proto3,enum=pipeline_msg.ProtobufPipelineMessage_MetricType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ProtobufPipelineMessage_Metric) Reset()         { *m = ProtobufPipelineMessage_Metric{} }
func (m *ProtobufPipelineMessage_Metric) String() string { return proto.CompactTextString(m) }
func (*ProtobufPipelineMessage_Metric) ProtoMessage()    {}
func (*ProtobufPipelineMessage_Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_622390471881ba1d, []int{0, 1}
}

func (m *ProtobufPipelineMessage_Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtobufPipelineMessage_Metric.Unmarshal(m, b)
}
func (m *ProtobufPipelineMessage_Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtobufPipelineMessage_Metric.Marshal(b, m, deterministic)
}
func (m *ProtobufPipelineMessage_Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtobufPipelineMessage_Metric.Merge(m, src)
}
func (m *ProtobufPipelineMessage_Metric) XXX_Size() int {
	return xxx_messageInfo_ProtobufPipelineMessage_Metric.Size(m)
}
func (m *ProtobufPipelineMessage_Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtobufPipelineMessage_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_ProtobufPipelineMessage_Metric proto.InternalMessageInfo

func (m *ProtobufPipelineMessage_Metric) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ProtobufPipelineMessage_Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ProtobufPipelineMessage_Metric) GetType() ProtobufPipelineMessage_MetricType {
	if m != nil {
		return m.Type
	}
	return ProtobufPipelineMessage_COUNTER
}

func init() {
	proto.RegisterEnum("pipeline_msg.ProtobufPipelineMessage_Vertical", ProtobufPipelineMessage_Vertical_name, ProtobufPipelineMessage_Vertical_value)
	proto.RegisterEnum("pipeline_msg.ProtobufPipelineMessage_LogLevel", ProtobufPipelineMessage_LogLevel_name, ProtobufPipelineMessage_LogLevel_value)
	proto.RegisterEnum("pipeline_msg.ProtobufPipelineMessage_MetricType", ProtobufPipelineMessage_MetricType_name, ProtobufPipelineMessage_MetricType_value)
	proto.RegisterType((*ProtobufPipelineMessage)(nil), "pipeline_msg.ProtobufPipelineMessage")
	proto.RegisterType((*ProtobufPipelineMessage_Field)(nil), "pipeline_msg.ProtobufPipelineMessage.Field")
	proto.RegisterType((*ProtobufPipelineMessage_Metric)(nil), "pipeline_msg.ProtobufPipelineMessage.Metrics")
}

func init() { proto.RegisterFile("pipeline_msg.proto", fileDescriptor_622390471881ba1d) }

var fileDescriptor_622390471881ba1d = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x86, 0x23, 0xdb, 0xfa, 0x1a, 0x97, 0x20, 0x96, 0x42, 0x16, 0x5f, 0x62, 0x4c, 0xa1, 0x86,
	0x16, 0xb9, 0xb8, 0x3d, 0xf4, 0xaa, 0x3a, 0xb2, 0x49, 0xea, 0x8f, 0xb0, 0xc8, 0xed, 0xd1, 0x28,
	0xf6, 0x44, 0x2c, 0x5d, 0x45, 0x42, 0x2b, 0x0b, 0xfc, 0x53, 0xfb, 0x6f, 0xca, 0xae, 0xa4, 0xa4,
	0x3d, 0x94, 0x24, 0xb7, 0x77, 0x76, 0xe6, 0x79, 0x67, 0xa4, 0x19, 0x20, 0x39, 0xcf, 0x51, 0xf0,
	0x07, 0xdc, 0xa5, 0x32, 0xf1, 0xf3, 0x22, 0x2b, 0x33, 0xf2, 0xe6, 0xef, 0xb7, 0xc1, 0x65, 0x92,
	0x65, 0x89, 0xc0, 0x89, 0xce, 0xdd, 0x1d, 0xef, 0x27, 0x25, 0x4f, 0x51, 0x96, 0x71, 0x9a, 0xd7,
	0xe5, 0xa3, 0xdf, 0x16, 0x5c, 0xdc, 0x36, 0xc9, 0xdb, 0x86, 0x5c, 0xa1, 0x94, 0x71, 0x82, 0x84,
	0x82, 0x5d, 0x61, 0x21, 0x79, 0xf6, 0x40, 0x8d, 0xa1, 0x31, 0x36, 0x59, 0x1b, 0x92, 0x4b, 0xe8,
	0xe7, 0x45, 0x76, 0x38, 0xee, 0xb1, 0xd8, 0xf1, 0x03, 0xed, 0x0c, 0x8d, 0xb1, 0xcb, 0xa0, 0x7d,
	0xba, 0x3e, 0x90, 0xaf, 0xe0, 0x3e, 0x76, 0xa2, 0xdd, 0xa1, 0x31, 0xee, 0x4f, 0x07, 0x7e, 0x3d,
	0x8b, 0xdf, 0xce, 0xe2, 0x47, 0x6d, 0x05, 0x7b, 0x2a, 0x56, 0x4d, 0x6b, 0x9f, 0x92, 0xf6, 0xb4,
	0x6d, 0x1b, 0x12, 0x02, 0xbd, 0x12, 0xe3, 0x94, 0x9a, 0xfa, 0x59, 0x6b, 0x55, 0x2d, 0xb1, 0xa8,
	0xf8, 0x1e, 0xa9, 0x55, 0x57, 0x37, 0x21, 0xb9, 0x01, 0xa7, 0xc2, 0xa2, 0xe4, 0xfb, 0x58, 0x50,
	0x7b, 0x68, 0x8c, 0xcf, 0xa7, 0xbe, 0xff, 0xcf, 0xef, 0xfa, 0xcf, 0x57, 0xfb, 0x3f, 0x1a, 0x8a,
	0x3d, 0xf2, 0xe4, 0x3b, 0xb8, 0x22, 0x4b, 0x76, 0x02, 0x2b, 0x14, 0xd4, 0x79, 0x8d, 0xd9, 0x32,
	0x4b, 0x96, 0x8a, 0x62, 0x8e, 0x68, 0x14, 0xb9, 0x00, 0x5b, 0x99, 0xa5, 0x32, 0xa1, 0xae, 0x1e,
	0xd9, 0x12, 0x59, 0xb2, 0x92, 0x09, 0x99, 0x81, 0x75, 0xcf, 0x51, 0x1c, 0x24, 0x85, 0x61, 0x77,
	0xdc, 0x9f, 0x7e, 0x78, 0x59, 0x8b, 0xb9, 0x62, 0x58, 0x83, 0x92, 0x39, 0xd8, 0x29, 0x96, 0x05,
	0xdf, 0x4b, 0xda, 0xd7, 0x2e, 0x1f, 0x5f, 0xe6, 0xb2, 0xd2, 0x10, 0x6b, 0xe1, 0xc1, 0x04, 0x4c,
	0x6d, 0x4c, 0x3c, 0xe8, 0xfe, 0xc2, 0x93, 0x3e, 0x00, 0x97, 0x29, 0x49, 0xde, 0x82, 0x59, 0xc5,
	0xe2, 0x88, 0xcd, 0xda, 0xeb, 0x60, 0x50, 0x81, 0x55, 0x7b, 0x3c, 0x47, 0x18, 0x0d, 0x41, 0xae,
	0xa0, 0x57, 0x9e, 0x72, 0xd4, 0xe7, 0x71, 0x3e, 0xfd, 0xf4, 0x9a, 0x39, 0xa3, 0x53, 0x8e, 0x4c,
	0xd3, 0xa3, 0xf7, 0xe0, 0xb4, 0x1b, 0x23, 0x0e, 0xf4, 0xb8, 0x9c, 0x7e, 0xf1, 0xce, 0x94, 0x8a,
	0x95, 0x32, 0x88, 0x0d, 0x5d, 0x25, 0x3a, 0xa3, 0x1b, 0x70, 0xda, 0x6d, 0x10, 0x17, 0xcc, 0x88,
	0x05, 0xb3, 0xd0, 0x3b, 0x53, 0xf2, 0x2a, 0xfc, 0xb6, 0x5d, 0x78, 0x86, 0x82, 0xae, 0xd7, 0xf3,
	0x8d, 0xd7, 0x51, 0xea, 0x67, 0xc0, 0xd6, 0x5e, 0x57, 0xa5, 0x43, 0xc6, 0x36, 0xcc, 0xeb, 0x29,
	0x39, 0x0f, 0xa2, 0x60, 0xe9, 0x99, 0xa3, 0x77, 0x00, 0x4f, 0x83, 0x90, 0x3e, 0xd8, 0xb3, 0xcd,
	0x76, 0x1d, 0x85, 0xac, 0xf6, 0x5b, 0x04, 0xdb, 0x45, 0xe8, 0x19, 0x77, 0x96, 0xbe, 0xf4, 0xcf,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x69, 0xc3, 0x69, 0x6a, 0xa7, 0x03, 0x00, 0x00,
}
